### ISSUE TITLE
GA should support to override iggy config with env vars

### ISSUE THREAD

**Issue by Tchoupinax** [iggy-rs/setup-iggy#14]

**Comment by Tchoupinax** [comment]
Nothing to implement in the Github Action, we can just provide environment variables to the action and it will be read by iggy server:

```yaml
- name: Setup iggy
  uses: iggy-rs/setup-iggy@v1
  env:
    IGGY_TCP_ADDRESS: "0.0.0.0:8091"
```
Every configuration can be overridden by environment variable following the pattern `IGGY_*`. Documentation can be found [here](https://docs.iggy.rs/server/configuration#configuration).
